name: learing github actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setting up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: running golang file
        run: go run main.go
        env:
          PORT: 8080
